

/****** Object:  Database [tictactoe]    Script Date: 2023-03-01 9:03:42 AM ******/
CREATE DATABASE [tictactoe]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'tictactoe', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\tictactoe.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'tictactoe_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\tictactoe_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT

GO


CREATE TABLE [dbo].[tic-tac-toe](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[playBoard] [varchar](50) NULL,
 CONSTRAINT [PK_tic-tac-toe] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

